# Generated by Django 5.0 on 2024-09-04 08:18

import django.contrib.admin.widgets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapp', '0002_alter_book_year_alter_student_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.DateField(verbose_name=django.contrib.admin.widgets.AdminDateWidget),
        ),
        migrations.AlterField(
            model_name='librarytransaction',
            name='end_date',
            field=models.DateField(verbose_name=django.contrib.admin.widgets.AdminDateWidget),
        ),
        migrations.AlterField(
            model_name='librarytransaction',
            name='start_date',
            field=models.DateField(verbose_name=django.contrib.admin.widgets.AdminDateWidget),
        ),
    ]
